In [117]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors

In [118]:
df = pd.read_csv('imdb_csv.csv')
df.head(5)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [119]:
#vectorizer = CountVectorizer()
#vector = vectorizer.fit_transform(df["Genre"])
#df_Genre = pd.DataFrame(vector.toarray(), columns=vectorizer.get_feature_names_out(), index=df.index)
#df = pd.concat((df, df_Genre), axis=1)

In [120]:
df.drop(columns=['Poster_Link', 'Released_Year', 'Certificate',
                 'Runtime', 'IMDB_Rating', 'Overview', 'Meta_score',
                 'No_of_Votes', 'Gross'], inplace=True)
df.head(5)

,Series_Title,Genre,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

In [121]:
split_Genre = df["Genre"].str.get_dummies(sep=", ")
df = pd.concat((df, split_Genre), axis=1)
df = df.drop(columns='Genre')

In [122]:
columns = ['Director','Star1','Star2','Star3','Star4']
df[columns] = df[columns].apply(lambda x: x.str.replace(" ", "_"), axis=1)

In [123]:
encoder = LabelEncoder()
col = ['Director','Star1','Star2','Star3','Star4']
for i in col:
    df[i] = encoder.fit_transform(df[i])

In [124]:
df

,Series_Title,Director,Star1,Star2,Star3,Star4,Action,Adventure,Animation,Biography,...,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,The Shawshank Redemption,141,599,568,89,912,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,The Godfather,137,417,9,336,194,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,The Dark Knight,83,128,283,1,620,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,The Godfather: Part II,137,9,657,704,194,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,12 Angry Men,456,252,464,535,421,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,50,50,260,633,114,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
996,Giant,164,185,668,337,134,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
997,From Here to Eternity,145,96,566,185,212,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
998,Lifeboat,22,588,392,867,908,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
999,The 39 Steps,22,515,487,510,294,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [125]:
def movie(name):
    nearst = NearestNeighbors(n_neighbors=10, algorithm="brute")
    new_film = df[(df['Series_Title'] == name)]
    x_new_film = new_film.drop(columns=['Series_Title'])
    df_new = df.drop(columns=['Series_Title'])
    nearst.fit(df_new)
    sim_film = nearst.kneighbors(x_new_film)
    return df.iloc[sim_film[1][0][1:]]['Series_Title']

In [126]:
movie('The Godfather')

568                     Nosferatu
297                 Jungfrukällan
217                Ford v Ferrari
599    How to Train Your Dragon 2
721             God's Own Country
602          Ang-ma-reul bo-at-da
833             Der Name der Rose
866          Les yeux sans visage
27                          Se7en
Name: Series_Title, dtype: str